#!/usr/bin/env bash


progress-bar() {

	local current=$1
	
	local len=$2

	local bar_char='#' #control show character
	local empty_char='.' #control empty character

	local length=50

	local perc_done=$((current*100/len))

	local num_bars=$((perc_done*length/100))

	# echo "processing $i/$len ($perc_done%)"

	local i=0
	local s='['

	for ((i=0; i< num_bars;i++)); do
		s+="$bar_char"
	done

	for ((i=num_bars; i< length;i++)); do
		s+="$empty_char"

	done
	s+=']'

	echo -ne "$s $current/$len ($perc_done%)\r"
}


process-file() {
	local files=("$@")

	echo rm ."${files[@]}" #show remove files,but not really remove

	sleep .01
}


shopt -s globstar nullglob

echo 'finding files'


files=(./**/*cache) #check target files

len=${#files[@]}

echo "found $len files"

batchsize=5
i=0
for ((i=0; i< len ;i+=batchsize)); do
	progress-bar "$(($i+1))" "$len"
	process-file "${files[@]:i:batchsize}"
done

progress-bar "$len" "$len"

echo
# for file in "${files[@]}" ; do
# 	progress-bar "$(($i+1))" "$len"
# 	process-file "$file"
# 	# echo "$file"
# 	((i++))

# done



